apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-generator
  namespace: observability  
  labels:
    app: trace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-generator
  template:
    metadata:
      labels:
        app: trace-generator
    spec:
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        args:
          - traces
          - --otlp-insecure
          - --otlp-endpoint=tempo.observability:4317
          - --rate=10        # Generate 10 traces per second
          - --duration=1000h # Run for a long time
        resources:
          limits:
            cpu: 100m
            memory: 100Mi