apiVersion: batch/v1
kind: CronJob
metadata:
  name: trace-generator
  namespace: observability
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: telemetrygen
            image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.142.0
            args:
              - traces
              - --otlp-insecure
              - --otlp-http
              - --otlp-endpoint=tempo.observability:4318
              - --traces=1
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
          restartPolicy: OnFailure